/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package gofs */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 32 "gofs.go"

#include <stdlib.h>
#include <string.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// CreateDir creates a new directory in the virtual filesystem.
// It can create nested directories recursively if they don't exist.
//
// Parameters:
//   - dirPath: A C-style string representing the full path of the directory to create.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -10: A file with the same name as one of the directory components already exists.
//   - -11: Failed to create a directory on the virtual disk.
//   - Other negative values: Error saving the filesystem table.
extern int CreateDir(char* dirPath);

// CopyFileToFS copies a file from the host operating system into the virtual filesystem.
// The file is encrypted on-the-fly during the copy process.
//
// Parameters:
//   - srcPath: A C-style string representing the path of the source file on the host OS.
//   - dstPath: A C-style string representing the full destination path in the virtual filesystem.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -3: Failed to open the source file on the host OS.
//   - -4: Failed to generate a random encryption key.
//   - -5: Failed to create a new AES cipher block.
//   - -6: Failed to generate a random initialization vector (IV).
//   - -7: Failed to create the destination file in the virtual filesystem.
//   - -8: Error during the encryption and copy process.
//   - -9: Failed to get source file information.
//   - -10: A file or directory with the same destination path already exists.
//   - -12: The destination directory does not exist in the virtual filesystem.
//   - Other negative values: Error saving the filesystem table.
extern int CopyFileToFS(char* srcPath, char* dstPath);

// CopyFileFromFS copies a file from the virtual filesystem to the host operating system.
// The file is decrypted on-the-fly during the copy process.
//
// Parameters:
//   - srcPath: A C-style string representing the full path of the source file in the virtual filesystem.
//   - dstPath: A C-style string representing the destination path on the host OS.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -15: Source file not found in the virtual filesystem or it is a directory.
//   - -16: Failed to decode the file's encryption key.
//   - -17: Failed to decode the file's initialization vector (IV).
//   - -18: Failed to create a new AES cipher block.
//   - -19: Failed to open the source file in the virtual filesystem.
//   - -20: Failed to create the destination file on the host OS.
//   - -21: Error during the decryption and copy process.
extern int CopyFileFromFS(char* srcPath, char* dstPath);

// DeleteFile deletes a file from the virtual filesystem.
//
// Parameters:
//   - filePath: A C-style string representing the full path of the file to delete.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -15: File not found or the path points to a directory.
//   - -22: Failed to remove the file from the virtual filesystem.
//   - Other negative values: Error saving the filesystem table.
extern int DeleteFile(char* filePath);

// RenameFile changes the name of a file within the same directory.
//
// Parameters:
//   - oldPath: A C-style string representing the current full path of the file.
//   - newPath: A C-style string representing the new full path of the file.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//	 - -2: Failed to get filesystem
//   - -7: Failed to create destination file
//   - -8: Failed to copy content
//   - -10: Destination path already exists.
//   - -12: Destination directory not found.
//   - -15: Source file not found or not a file.
//   - -19: Failed to open source file
//   - -22: Failed to remove original file
//   - Other negative values: Error saving the filesystem table.
extern int RenameFile(char* oldPath, char* newPath);

// MoveFile moves a file from one path to another. This function is an alias for RenameFile.
//
// Parameters:
//   - fullPathSource: A C-style string representing the current full path of the file.
//   - fullPathTarget: A C-style string representing the new full path for the file.
//
// Returns:
//   - See RenameFile for return codes.
extern int MoveFile(char* fullPathSource, char* fullPathTarget);

// DeleteFolder removes an empty directory from the virtual filesystem.
// The directory must be empty before it can be deleted.
//
// Parameters:
//   - folderPath: A C-style string representing the full path of the folder to delete.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -22: Failed to remove the directory from the virtual filesystem.
//   - -23: The directory is not empty.
//   - -24: The folder was not found or the path does not point to a directory.
//   - -25: Attempted to delete the root directory ("/"), which is not allowed.
//   - Other negative values: Error saving the filesystem table.
extern int DeleteFolder(char* folderPath);

// EmptyFolder recursively deletes all files and subfolders within a given directory.
//
// Parameters:
//   - folderPath: A C-style string representing the full path of the folder to empty.
//
// Returns:
//   - 0: Success, or if the folder was already empty.
//   - -1: Session is not open.
//   - -2: Failed to get the filesystem handle.
//   - -22: Failed to remove an item from the virtual filesystem during the deletion process.
//   - -24: The specified folder was not found or is not a directory.
//   - Other negative values: Error saving the filesystem table.
extern int EmptyFolder(char* folderPath);

// ListFile lists the contents of a directory or finds files matching a pattern.
//
// Parameters:
//   - searchPattern: A C-style string. If it's a plain path, it lists the directory's
//     contents. If it includes wildcards (*, ?), it searches for matching file/folder names
//     within the parent directory of the pattern.
//
// Returns:
//   - A C-style string containing a JSON array of FileInfo objects.
//   - On error, it returns a JSON object with an "error" key, e.g.,
//     `{"error": "session not open"}` or `{"error": "failed to marshal results"}`.
extern char* ListFile(char* searchPattern);

// CopyFileMapDecrypted copies the filesystem table (fstab) to the host OS and decrypts it.
// The result is a human-readable JSON file representing the filesystem's metadata.
//
// Parameters:
//   - dstPath: A C-style string representing the destination path on the host OS.
//
// Returns:
//   - 0: Success.
//   - -1: Failed to get the filesystem handle.
//   - -3: Failed to open the source fstab file in the virtual filesystem.
//   - -4: Failed to create the destination file on the host OS.
//   - -10: Failed to read the encrypted fstab content.
//   - -11: The filesystem table encryption key is not loaded.
//   - -13: Failed to create the AES cipher block for decryption.
//   - -14: Failed to write the decrypted content to the destination file.
extern int CopyFileMapDecrypted(char* dstPath);

// GetDiskSpaceInfo returns information about the disk usage of the virtual filesystem.
//
// Returns:
//   - A C-style string containing a JSON object with "total", "used", and "free" space in bytes.
//   - On error, it returns a JSON object with an "error" key, e.g.,
//     `{"error": "session not open"}` or `{"error": "failed to get disk file stats"}`.
extern char* GetDiskSpaceInfo(void);

// BackupFileSystem creates a backup of the entire virtual disk container file.
// The backup is named with a timestamp, e.g., "myDisk.fs.20231027-150405.bak".
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: The source filesystem file does not exist or the path is not set.
//   - -3: Failed to open the source file.
//   - -4: Failed to create the backup file.
//   - -5: Failed to copy the content to the backup file.
extern int BackupFileSystem(void);

// DangerFormatDisk creates a new, empty virtual disk file, overwriting any existing one.
// This is a destructive operation and will result in the loss of all data in the
// current filesystem. It also creates the first user account with the current
// session's credentials.
//
// Parameters:
//   - size: The desired size of the new virtual disk in bytes.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Failed to create the disk file or generate a new master key.
//   - -3: Failed to create the FAT32 filesystem on the disk.
//   - -26: Failed to remove the existing disk file before creating a new one.
//   - -27: Failed to create the /keys directory.
//   - -29: Failed to create the /system directory.
//   - Other negative values: Error saving the new filesystem table or user key.
extern int DangerFormatDisk(GoInt64 size);

// DangerDeleteFileSystemFile permanently deletes the virtual disk container file from the host OS.
// This is a destructive operation and will result in the loss of all data. The session
// is forcibly closed before deletion to release any file locks.
//
// Returns:
//   - 0: Success, or if the file did not exist.
//   - -1: Failed to delete the file (e.g., due to permissions).
extern int DangerDeleteFileSystemFile(void);

// InitSession initializes a new session, effectively "opening" the encrypted filesystem.
// It takes the necessary credentials, loads the filesystem metadata, and prepares the
// library for file operations. If the filesystem file doesn't exist, it prepares for
// the creation of a new one.
//
// Parameters:
//   - fileName: A C-style string with the path to the virtual disk container file.
//   - crKey: A C-style string representing the user's secret (password).
//   - key: A C-style string representing the username or key identifier.
//
// Returns:
//   - 0: Success.
//   - -1: One of the required parameters is nil.
//   - -2: One of the required parameters is an empty string, or failed to get the filesystem handle.
//   - -5: Wrong secret (password).
//   - Other negative values: Errors during the loading of filesystem keys or metadata.
extern int InitSession(char* fileName, char* crKey, char* key);

// IsSessionOpen checks if a session is currently active.
//
// Returns:
//   - true: If a session is open.
//   - false: If no session is open.
extern GoUint8 IsSessionOpen(void);

// ChangePassword allows the current user to change their password.
// It requires an active session and re-encrypts the user's key file with the
// new password.
//
// Parameters:
//   - newPassword: A C-style string for the new password.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Invalid new password (empty) or failed to get FS handle.
//   - Other negative values: Errors from the key saving process.
extern int ChangePassword(char* newPassword);

// AddUser allows a currently logged-in user to grant access to a new user.
// It encrypts the master filesystem key with the new user's credentials and
// creates a new key file for them.
//
// Parameters:
//   - newUserName: A C-style string for the new user's name.
//   - newUserPassword: A C-style string for the new user's password.
//
// Returns:
//   - 0: Success.
//   - -1: Session is not open.
//   - -2: Invalid parameters (empty username or password) or failed to get FS handle.
//   - -5: Encryption error.
//   - -11: The master key is not loaded in the current session.
//   - -27: Failed to create the /keys directory.
//   - -30: The specified user already exists.
extern int AddUser(char* newUserName, char* newUserPassword);

// CloseSession terminates the current session, clearing all sensitive data from memory,
// including keys and the filesystem map. This securely "closes" the filesystem.
//
// Returns:
//   - 0: Always returns 0.
extern int CloseSession(void);

#ifdef __cplusplus
}
#endif
